Dir {
  ArchiveDir "apt";
  CacheDir "/tmp/apt-ftparchive-cache";
};

Default {
  Packages::Compress ". gzip xz";
};

BinDirectory "pool/main" {
  Packages "dists/stable/main/binary-amd64/Packages";
  Architecture "amd64";
};

BinDirectory "pool/main" {
  Packages "dists/stable/main/binary-arm64/Packages";
  Architecture "arm64";
};
